#spring:
#  cloud:
#    gateway:
#      routes:
#        - id : r1
#          uri : http://localhost:8888/
#          predicates :
#            - Path= /customers/**
#        - id : r2
#          uri : http://localhost:8889/
#          predicates :
#            - Path= /products/**